from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import cv2

class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        if not RegisterWindow.objectName():
            RegisterWindow.setObjectName(u"RegisterWindow")
        RegisterWindow.resize(700, 650)
        RegisterWindow.setMinimumSize(QSize(700, 650))
        RegisterWindow.setMaximumSize(QSize(700, 650))
        RegisterWindow.setCursor(QCursor(Qt.PointingHandCursor))
        self.centralwidget = QWidget(RegisterWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayoutWidget_2 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(70, 580, 481, 51))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pushButton = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setMinimumSize(QSize(0, 40))
        self.pushButton.setMaximumSize(QSize(16777215, 40))
        font = QFont()
        font.setFamily(u"Cascadia Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(u"color:#fff;\n""background-color:rgb(85, 0, 255);\n""border-radius:18;")

        self.verticalLayout_2.addWidget(self.pushButton)

        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(70, 20, 541, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(u"label")
        self.label.setFont(font)
        self.label.setStyleSheet(u"color:rgb(85, 0, 255);")

        self.horizontalLayout.addWidget(self.label)

        self.lineEdit = QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setMaximumSize(QSize(16777215, 40))
        font1 = QFont()
        font1.setFamily(u"Segoe UI")
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setItalic(True)
        font1.setWeight(75)
        self.lineEdit.setFont(font1)

        self.horizontalLayout.addWidget(self.lineEdit)

        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 70, 231, 31))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color:rgb(85, 0, 255);")
        self.horizontalLayoutWidget_2 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(70, 100, 541, 42))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pushButton_2 = QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setMinimumSize(QSize(0, 40))
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QCursor(Qt.OpenHandCursor))
        self.pushButton_2.setStyleSheet(u"color:rgb(0, 170, 255)")

        self.horizontalLayout_2.addWidget(self.pushButton_2)

        self.label_3 = QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMaximumSize(QSize(16777215, 40))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setWeight(75)
        self.label_3.setFont(font2)
        self.label_3.setStyleSheet(u"color:rgb(255, 0, 255)")

        self.horizontalLayout_2.addWidget(self.label_3)

        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(70, 160, 501, 41))
        font3 = QFont()
        font3.setFamily(u"Sitka Subheading")
        font3.setPointSize(16)
        font3.setBold(False)
        font3.setItalic(False)
        font3.setWeight(50)
        self.label_4.setFont(font3)
        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(70, 220, 431, 283))
        self.FacialOptionBox = QGridLayout(self.gridLayoutWidget)
        self.FacialOptionBox.setObjectName(u"FacialOptionBox")
        self.FacialOptionBox.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMinimumSize(QSize(320, 240))

        self.FacialOptionBox.addWidget(self.label_5, 0, 0, 1, 1)

        self.CaptureButton = QPushButton(self.gridLayoutWidget)
        self.CaptureButton.setObjectName(u"CaptureButton")
        self.CaptureButton.setMaximumSize(QSize(120, 40))
        font4 = QFont()
        font4.setFamily(u"Segoe Script")
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setWeight(75)
        self.CaptureButton.setFont(font4)
        self.CaptureButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.CaptureButton.setStyleSheet(u"color:rgb(255, 0, 127);")

        self.FacialOptionBox.addWidget(self.CaptureButton, 1, 0, 1, 1)

        self.TrainButton = QPushButton(self.centralwidget)
        self.TrainButton.setObjectName(u"TrainButton")
        self.TrainButton.setGeometry(QRect(70, 520, 200, 40))
        self.TrainButton.setMinimumSize(QSize(200, 0))
        self.TrainButton.setMaximumSize(QSize(200, 40))
        self.TrainButton.setFont(font4)
        self.TrainButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.TrainButton.setStyleSheet(u"color:rgb(235, 0, 227);")
  

        self.retranslateUi(RegisterWindow)

        QMetaObject.connectSlotsByName(RegisterWindow)
    # setupUi

    def retranslateUi(self, RegisterWindow):
        RegisterWindow.setWindowTitle(QCoreApplication.translate("RegisterWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("RegisterWindow", u"SUBMIT", None))
        self.label.setText(QCoreApplication.translate("RegisterWindow", u"ENTER NAME", None))
        self.label_2.setText(QCoreApplication.translate("RegisterWindow", u"FINGERPRINT CONFIG", None))
        self.pushButton_2.setText(QCoreApplication.translate("RegisterWindow", u"CONNECT", None))
        self.label_3.setText(QCoreApplication.translate("RegisterWindow", u".", None))
        self.label_4.setText("")
        self.label_5.setText("")
        self.CaptureButton.setText(QCoreApplication.translate("RegisterWindow", u"CAPTURE", None))
        self.TrainButton.setText(QCoreApplication.translate("RegisterWindow", u"TRAIN", None))
    # retranslateUi

